services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: daniscoder/devops-for-developers-project-74
    command: make test
    environment:
      - NODE_ENV=test
